/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#849588",
        "surface-variant": "#303635",
        "primary-fixed": "#50ffaf",
        "secondary-fixed-dim": "#ffb956",
        "surface-container": "#1b2120",
        "background": "#0f1513",
        "on-secondary-container": "#3d2500",
        "surface-dim": "#0f1513",
        "inverse-surface": "#dee4e1",
        "on-primary-fixed-variant": "#005232",
        "on-tertiary-fixed-variant": "#394a46",
        "surface-container-low": "#171d1c",
        "on-secondary-fixed-variant": "#633f00",
        "tertiary-fixed-dim": "#b7cbc5",
        "on-primary-fixed": "#002111",
        "surface-container-highest": "#303635",
        "surface-bright": "#343a39",
        "on-secondary": "#452b00",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "primary": "#cdffde",
        "on-primary-container": "#006b43",
        "surface-container-lowest": "#090f0e",
        "on-background": "#dee4e1",
        "inverse-on-surface": "#2b3230",
        "primary-container": "#00f5a0",
        "outline-variant": "#3b4a40",
        "on-tertiary": "#233430",
        "secondary-container": "#c58311",
        "on-tertiary-fixed": "#0e1f1c",
        "on-tertiary-container": "#4f615d",
        "secondary-fixed": "#ffddb5",
        "on-primary": "#003921",
        "primary-fixed-dim": "#00e293",
        "on-secondary-fixed": "#2a1800",
        "surface": "#0f1513",
        "tertiary-fixed": "#d3e7e1",
        "tertiary-container": "#c8dbd6",
        "error": "#ffb4ab",
        "surface-tint": "#00e293",
        "secondary": "#ffb956",
        "on-surface": "#dee4e1",
        "surface-container-high": "#252b2a",
        "tertiary": "#e4f8f2",
        "on-surface-variant": "#b9cbbd",
        "inverse-primary": "#006c44",
        "error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "container-padding-mobile": "20px",
        "container-padding-desktop": "48px",
        "gutter": "24px",
        "section-gap": "80px",
        "margin-mobile": "20px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "container-max": "1200px"
      },
      fontFamily: {
        "headline-sm": ["Montserrat"],
        "body-lg": ["Be Vietnam Pro"],
        "label-caps": ["Space Grotesk"],
        "headline-md": ["Montserrat"],
        "display-lg": ["Montserrat"],
        "display-lg-mobile": ["Montserrat"],
        "body-md": ["Be Vietnam Pro"]
      },
      fontSize: {
        "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "900" }],
        "display-lg-mobile": ["36px", { "lineHeight": "1.2", "fontWeight": "900" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
